export const projects = [
  {
    title: 'Chat App',
    description: "Users can chat with doctors with one-on-one feature & can share their location too & hosted at heroku platform.",
      image: '/images/Chat App.png',
      tags: ['MongoDB', 'Express', 'Node.js'],
    source: 'https://github.com/Parthudi/chat-app',
    visit: 'https://parthudi-chat-app.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Humans Wear',
    description:"Users can see products with nice ui, can add to cart, add to wishlist, as e-commerce site based on clothing. For ui purpose Material UI is used.",
    image: '/images/humans Wear.png',
    tags: ['React.js', 'Express', 'MongoDB', 'Node.js', 'JavaScript'],
    source: 'https://github.com/Parthudi/Humans_Wear',
    visit: 'https://github.com/Parthudi/Humans_Wear',
    id: 1,
  },
  {
    title: 'Bookie-store',
    description: "Users can see products with nice, different kinds of sorting are added, add to cart features are also there, as e-commerce site based on book. Here all the images and data are stored in mongodb and For ui purpose Bootstrap is used.",
      image: '/images/BookieCommerce.png',
      tags: ['React.js', 'Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/Parthudi/bookStore',
    visit: 'https://github.com/Parthudi/bookStore',
    id: 2,
  },
  {
    title: 'Monsters Hunt',
    description: "Users can view ui for monsters and they can even search the monsters by there name.",
    image: '/images/Monsters Hunt.png',
    tags: ['React.js'],
    source: 'https://github.com/Parthudi/monsters-hunt',
    visit: 'https://github.com/Parthudi/monsters-hunt',
    id: 3,
  },
  {
    title: 'Humans Burger',
    description: "Users can make their own burgers by adding different things to it and for data saving purpose firebase is used. Users can see their past orders history & hosted at GitHub pages. ",
    image: '/images/Humans Burger.png',
    tags: ['React.js'],
    source: 'https://github.com/Parthudi/humansBurger',
    visit: 'https://github.com/Parthudi/humansBurger',
    id: 4,
  },
  {
    title: 'WhatsApp Services',
    description: "Users can scan QR code and then send WhatsApp message to only some admin added users, can add peoples in the company, & can create groups and have chat & for data storage purpose mongo dB is used & for ui & Responsive purpose Material UI is used. ",
    image: '/images/Whatsapp Services.png',
    tags: ['React.js', 'Node.js', 'MongoDB', 'Express.js'],
    source: 'https://github.com/Parthudi/whatsapp',
    visit: 'https://github.com/Parthudi/whatsapp',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Started my journey by joining Marsilex as an intern', month: '[ jul - sept ]'},
  { year: 2021, text: 'Started my job as a Software Developer || Software Engineer at Vistaura', month: `[ Feb - Oct]`},
  { year: 2021, text: 'Started my job as a Software Developer || Software Engineer at Vistaura', month: `[ Oct - Present]`},
];